# Generated by Django 4.2.2 on 2024-06-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Department_Details',
        ),
        migrations.RenameModel(
            old_name='Description',
            new_name='Doctor',
        ),
    ]
