# Generated by Django 4.2.2 on 2024-06-05 18:28

from django.db import migrations, models
import providers.models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_service_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='depimg',
            field=models.ImageField(blank=True, upload_to=providers.models.jump_and_name, verbose_name='Jump Profile'),
        ),
    ]
