# Generated by Django 4.2.2 on 2024-06-05 18:46

from django.db import migrations, models
import django.db.models.deletion
import providers.models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_department_depimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description_id',
            new_name='doctor_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_pic',
            field=models.ImageField(blank=True, upload_to=providers.models.jumps_and_name, verbose_name='Provider Profile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc', to='providers.department'),
        ),
    ]
