# Generated by Django 4.2.2 on 2024-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_rename_description_id_doctor_doctor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='about',
        ),
        migrations.RemoveField(
            model_name='department_details',
            name='name',
        ),
        migrations.AddField(
            model_name='department_details',
            name='about',
            field=models.TextField(blank=True, max_length=900),
        ),
    ]
