# Generated by Django 4.2.2 on 2024-06-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_remove_department_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_details',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
