# Generated by Django 4.2.2 on 2024-06-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_clientappointment_delete_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientappointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clientappointment',
            name='doctor_for',
        ),
        migrations.RemoveField(
            model_name='clientappointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clientappointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientappointment',
            name='reason_for_appointment',
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientappointment',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientappointment',
            name='date_of_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientappointment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientappointment',
            name='time_of_appointment',
            field=models.TimeField(null=True),
        ),
    ]
