# Generated by Django 4.2.2 on 2023-10-01 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('profile_Pic', models.ImageField(blank=True, upload_to=services.models.path_and_rename, verbose_name='Profile Picture')),
                ('user_type', models.CharField(choices=[('service_subscriber', 'service_subscriber'), ('service_user', 'service_user'), ('servicer_provider', 'servicer_provider')], default='service_user', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
